name: Fetch and update Disneyland & DCA ride data

on:
  schedule:
    - cron: "*/10 15-23,0-7 * * *" # Runs every 10 minutes between 8 AM and midnight PST (15:00-07:00 UTC)
  workflow_dispatch: # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: "disneyland-ride-data"
      S3_ENDPOINT: "https://4c4a97248c0a97b4725084e66e0dc734.r2.cloudflarestorage.com"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run Script
        run: bun run index.ts
